# spin manifest — an application needs no [package] identity.
# Add dependencies like:
#   [dependencies]
#   ansi = { path = "../spinel-ansi" }

[dependencies]
sdl = { git = "https://github.com/jockofcode/sdl" }
